#############################################################################
# Makefile for building: bluesystem
# Generated by qmake (3.0) (Qt 5.0.2) on: lun nov 25 23:03:43 2013
# Project:  bluesystem.pro
# Template: subdirs
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile bluesystem.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		sub----ndlite-c---ndlite-pro \
		sub-src


sub----ndlite-c---ndlite-pro-qmake_all:  FORCE
	@test -d ../ndlite/c++/ || mkdir -p ../ndlite/c++/
	cd ../ndlite/c++/ && $(QMAKE) /home/shaka/Documents/dev/ndlite/c++/ndlite.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile.ndlite
	cd ../ndlite/c++/ && $(MAKE) -f Makefile.ndlite qmake_all
sub----ndlite-c---ndlite-pro: FORCE
	@test -d ../ndlite/c++/ || mkdir -p ../ndlite/c++/
	cd ../ndlite/c++/ && ( test -e Makefile.ndlite || $(QMAKE) /home/shaka/Documents/dev/ndlite/c++/ndlite.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile.ndlite ) && $(MAKE) -f Makefile.ndlite
sub----ndlite-c---ndlite-pro-make_first-ordered: FORCE
	@test -d ../ndlite/c++/ || mkdir -p ../ndlite/c++/
	cd ../ndlite/c++/ && ( test -e Makefile.ndlite || $(QMAKE) /home/shaka/Documents/dev/ndlite/c++/ndlite.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile.ndlite ) && $(MAKE) -f Makefile.ndlite 
sub----ndlite-c---ndlite-pro-make_first: FORCE
	@test -d ../ndlite/c++/ || mkdir -p ../ndlite/c++/
	cd ../ndlite/c++/ && ( test -e Makefile.ndlite || $(QMAKE) /home/shaka/Documents/dev/ndlite/c++/ndlite.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile.ndlite ) && $(MAKE) -f Makefile.ndlite 
sub----ndlite-c---ndlite-pro-all-ordered: FORCE
	@test -d ../ndlite/c++/ || mkdir -p ../ndlite/c++/
	cd ../ndlite/c++/ && ( test -e Makefile.ndlite || $(QMAKE) /home/shaka/Documents/dev/ndlite/c++/ndlite.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile.ndlite ) && $(MAKE) -f Makefile.ndlite all
sub----ndlite-c---ndlite-pro-all: FORCE
	@test -d ../ndlite/c++/ || mkdir -p ../ndlite/c++/
	cd ../ndlite/c++/ && ( test -e Makefile.ndlite || $(QMAKE) /home/shaka/Documents/dev/ndlite/c++/ndlite.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile.ndlite ) && $(MAKE) -f Makefile.ndlite all
sub----ndlite-c---ndlite-pro-clean-ordered: FORCE
	@test -d ../ndlite/c++/ || mkdir -p ../ndlite/c++/
	cd ../ndlite/c++/ && ( test -e Makefile.ndlite || $(QMAKE) /home/shaka/Documents/dev/ndlite/c++/ndlite.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile.ndlite ) && $(MAKE) -f Makefile.ndlite clean
sub----ndlite-c---ndlite-pro-clean: FORCE
	@test -d ../ndlite/c++/ || mkdir -p ../ndlite/c++/
	cd ../ndlite/c++/ && ( test -e Makefile.ndlite || $(QMAKE) /home/shaka/Documents/dev/ndlite/c++/ndlite.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile.ndlite ) && $(MAKE) -f Makefile.ndlite clean
sub----ndlite-c---ndlite-pro-distclean-ordered: FORCE
	@test -d ../ndlite/c++/ || mkdir -p ../ndlite/c++/
	cd ../ndlite/c++/ && ( test -e Makefile.ndlite || $(QMAKE) /home/shaka/Documents/dev/ndlite/c++/ndlite.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile.ndlite ) && $(MAKE) -f Makefile.ndlite distclean
sub----ndlite-c---ndlite-pro-distclean: FORCE
	@test -d ../ndlite/c++/ || mkdir -p ../ndlite/c++/
	cd ../ndlite/c++/ && ( test -e Makefile.ndlite || $(QMAKE) /home/shaka/Documents/dev/ndlite/c++/ndlite.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile.ndlite ) && $(MAKE) -f Makefile.ndlite distclean
sub----ndlite-c---ndlite-pro-install_subtargets-ordered: FORCE
	@test -d ../ndlite/c++/ || mkdir -p ../ndlite/c++/
	cd ../ndlite/c++/ && ( test -e Makefile.ndlite || $(QMAKE) /home/shaka/Documents/dev/ndlite/c++/ndlite.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile.ndlite ) && $(MAKE) -f Makefile.ndlite install
sub----ndlite-c---ndlite-pro-install_subtargets: FORCE
	@test -d ../ndlite/c++/ || mkdir -p ../ndlite/c++/
	cd ../ndlite/c++/ && ( test -e Makefile.ndlite || $(QMAKE) /home/shaka/Documents/dev/ndlite/c++/ndlite.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile.ndlite ) && $(MAKE) -f Makefile.ndlite install
sub----ndlite-c---ndlite-pro-uninstall_subtargets-ordered: FORCE
	@test -d ../ndlite/c++/ || mkdir -p ../ndlite/c++/
	cd ../ndlite/c++/ && ( test -e Makefile.ndlite || $(QMAKE) /home/shaka/Documents/dev/ndlite/c++/ndlite.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile.ndlite ) && $(MAKE) -f Makefile.ndlite uninstall
sub----ndlite-c---ndlite-pro-uninstall_subtargets: FORCE
	@test -d ../ndlite/c++/ || mkdir -p ../ndlite/c++/
	cd ../ndlite/c++/ && ( test -e Makefile.ndlite || $(QMAKE) /home/shaka/Documents/dev/ndlite/c++/ndlite.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile.ndlite ) && $(MAKE) -f Makefile.ndlite uninstall
sub-src-qmake_all: sub----ndlite-c---ndlite-pro-qmake_all FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && $(QMAKE) /home/shaka/Documents/dev/bluegear/src/src.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile
	cd src/ && $(MAKE) -f Makefile qmake_all
sub-src: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /home/shaka/Documents/dev/bluegear/src/src.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile
sub-src-make_first-ordered: sub----ndlite-c---ndlite-pro-make_first-ordered  FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /home/shaka/Documents/dev/bluegear/src/src.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-src-make_first: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /home/shaka/Documents/dev/bluegear/src/src.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-src-all-ordered: sub----ndlite-c---ndlite-pro-all-ordered  FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /home/shaka/Documents/dev/bluegear/src/src.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-src-all: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /home/shaka/Documents/dev/bluegear/src/src.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-src-clean-ordered: sub----ndlite-c---ndlite-pro-clean-ordered  FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /home/shaka/Documents/dev/bluegear/src/src.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-clean: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /home/shaka/Documents/dev/bluegear/src/src.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-distclean-ordered: sub----ndlite-c---ndlite-pro-distclean-ordered  FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /home/shaka/Documents/dev/bluegear/src/src.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-distclean: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /home/shaka/Documents/dev/bluegear/src/src.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-install_subtargets-ordered: sub----ndlite-c---ndlite-pro-install_subtargets-ordered  FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /home/shaka/Documents/dev/bluegear/src/src.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-src-install_subtargets: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /home/shaka/Documents/dev/bluegear/src/src.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-src-uninstall_subtargets-ordered: sub----ndlite-c---ndlite-pro-uninstall_subtargets-ordered  FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /home/shaka/Documents/dev/bluegear/src/src.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-src-uninstall_subtargets: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /home/shaka/Documents/dev/bluegear/src/src.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: bluesystem.pro /usr/share/qt5/mkspecs/linux-g++-64/qmake.conf /usr/share/qt5/mkspecs/features/spec_pre.prf \
		/usr/share/qt5/mkspecs/common/shell-unix.conf \
		/usr/share/qt5/mkspecs/common/unix.conf \
		/usr/share/qt5/mkspecs/common/linux.conf \
		/usr/share/qt5/mkspecs/common/gcc-base.conf \
		/usr/share/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt5/mkspecs/common/g++-base.conf \
		/usr/share/qt5/mkspecs/common/g++-unix.conf \
		/usr/share/qt5/mkspecs/qconfig.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_3d.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_bootstrap.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_clucene.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_designercomponents.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_platformsupport.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qmldevtools.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_quickparticles.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_v8.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/share/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/share/qt5/mkspecs/features/qt_functions.prf \
		/usr/share/qt5/mkspecs/features/qt_config.prf \
		/usr/share/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/share/qt5/mkspecs/features/spec_post.prf \
		/usr/share/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt5/mkspecs/features/default_pre.prf \
		/usr/share/qt5/mkspecs/features/unix/default_pre.prf \
		/usr/share/qt5/mkspecs/features/resolve_config.prf \
		/usr/share/qt5/mkspecs/features/default_post.prf \
		/usr/share/qt5/mkspecs/features/qml_debug.prf \
		/usr/share/qt5/mkspecs/features/declarative_debug.prf \
		/usr/share/qt5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt5/mkspecs/features/warn_on.prf \
		/usr/share/qt5/mkspecs/features/wayland-scanner.prf \
		/usr/share/qt5/mkspecs/features/testcase_targets.prf \
		/usr/share/qt5/mkspecs/features/exceptions.prf \
		/usr/share/qt5/mkspecs/features/yacc.prf \
		/usr/share/qt5/mkspecs/features/lex.prf \
		bluesystem.pro
	$(QMAKE) -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile bluesystem.pro
/usr/share/qt5/mkspecs/features/spec_pre.prf:
/usr/share/qt5/mkspecs/common/shell-unix.conf:
/usr/share/qt5/mkspecs/common/unix.conf:
/usr/share/qt5/mkspecs/common/linux.conf:
/usr/share/qt5/mkspecs/common/gcc-base.conf:
/usr/share/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt5/mkspecs/common/g++-base.conf:
/usr/share/qt5/mkspecs/common/g++-unix.conf:
/usr/share/qt5/mkspecs/qconfig.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_3d.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_3dquick.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_bootstrap.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_clucene.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_designercomponents.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_location.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_platformsupport.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_qmldevtools.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_quickparticles.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_sensors.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_v8.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/share/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/share/qt5/mkspecs/features/qt_functions.prf:
/usr/share/qt5/mkspecs/features/qt_config.prf:
/usr/share/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/share/qt5/mkspecs/features/spec_post.prf:
/usr/share/qt5/mkspecs/features/exclusive_builds.prf:
/usr/share/qt5/mkspecs/features/default_pre.prf:
/usr/share/qt5/mkspecs/features/unix/default_pre.prf:
/usr/share/qt5/mkspecs/features/resolve_config.prf:
/usr/share/qt5/mkspecs/features/default_post.prf:
/usr/share/qt5/mkspecs/features/qml_debug.prf:
/usr/share/qt5/mkspecs/features/declarative_debug.prf:
/usr/share/qt5/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt5/mkspecs/features/warn_on.prf:
/usr/share/qt5/mkspecs/features/wayland-scanner.prf:
/usr/share/qt5/mkspecs/features/testcase_targets.prf:
/usr/share/qt5/mkspecs/features/exceptions.prf:
/usr/share/qt5/mkspecs/features/yacc.prf:
/usr/share/qt5/mkspecs/features/lex.prf:
bluesystem.pro:
qmake: FORCE
	@$(QMAKE) -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile bluesystem.pro

qmake_all: sub----ndlite-c---ndlite-pro-qmake_all sub-src-qmake_all FORCE

make_first: sub----ndlite-c---ndlite-pro-make_first-ordered sub-src-make_first-ordered FORCE
all: sub----ndlite-c---ndlite-pro-all-ordered sub-src-all-ordered FORCE
clean: sub----ndlite-c---ndlite-pro-clean-ordered sub-src-clean-ordered FORCE
distclean: sub----ndlite-c---ndlite-pro-distclean-ordered sub-src-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub----ndlite-c---ndlite-pro-install_subtargets-ordered sub-src-install_subtargets-ordered FORCE
uninstall_subtargets: sub----ndlite-c---ndlite-pro-uninstall_subtargets-ordered sub-src-uninstall_subtargets-ordered FORCE

sub----ndlite-c---ndlite-pro-check_ordered:
	@test -d ../ndlite/c++/ || mkdir -p ../ndlite/c++/
	cd ../ndlite/c++/ && ( test -e Makefile.ndlite || $(QMAKE) /home/shaka/Documents/dev/ndlite/c++/ndlite.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile.ndlite ) && $(MAKE) -f Makefile.ndlite check
sub-src-check_ordered: sub----ndlite-c---ndlite-pro-check_ordered 
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /home/shaka/Documents/dev/bluegear/src/src.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile check
check: sub----ndlite-c---ndlite-pro-check_ordered sub-src-check_ordered
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

