#############################################################################
# Makefile for building: BlueSystem
# Generated by qmake (2.01a) (Qt 4.8.1) on: sáb 2. feb 03:22:19 2013
# Project:  BlueSystem.pro
# Template: subdirs
# Command: e:\dev\qtsdk\desktop\qt\4.8.1\mingw\bin\qmake.exe -spec e:\dev\QtSDK\Desktop\Qt\4.8.1\mingw\mkspecs\win32-g++ CONFIG+=declarative_debug -o Makefile BlueSystem.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = e:\dev\qtsdk\desktop\qt\4.8.1\mingw\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
SUBTARGETS    =  \
		sub-terminal \
		sub----Neodymium \
		sub-manager \
		sub-updater

terminal\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) terminal\ $(MKDIR) terminal\ 
	cd terminal\ && $(QMAKE) e:\shaka\dev\current\soft\BlueSystem\terminal\terminal.pro -spec e:\dev\QtSDK\Desktop\Qt\4.8.1\mingw\mkspecs\win32-g++ CONFIG+=declarative_debug -o $(MAKEFILE)
sub-terminal-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) terminal\ $(MKDIR) terminal\ 
	cd terminal\ && $(QMAKE) e:\shaka\dev\current\soft\BlueSystem\terminal\terminal.pro -spec e:\dev\QtSDK\Desktop\Qt\4.8.1\mingw\mkspecs\win32-g++ CONFIG+=declarative_debug -o $(MAKEFILE)
sub-terminal: terminal\$(MAKEFILE) FORCE
	cd terminal\ && $(MAKE) -f $(MAKEFILE)
sub-terminal-make_default-ordered: terminal\$(MAKEFILE) FORCE
	cd terminal\ && $(MAKE) -f $(MAKEFILE) 
sub-terminal-make_default: terminal\$(MAKEFILE) FORCE
	cd terminal\ && $(MAKE) -f $(MAKEFILE) 
sub-terminal-make_first-ordered: terminal\$(MAKEFILE) FORCE
	cd terminal\ && $(MAKE) -f $(MAKEFILE) first
sub-terminal-make_first: terminal\$(MAKEFILE) FORCE
	cd terminal\ && $(MAKE) -f $(MAKEFILE) first
sub-terminal-all-ordered: terminal\$(MAKEFILE) FORCE
	cd terminal\ && $(MAKE) -f $(MAKEFILE) all
sub-terminal-all: terminal\$(MAKEFILE) FORCE
	cd terminal\ && $(MAKE) -f $(MAKEFILE) all
sub-terminal-clean-ordered: terminal\$(MAKEFILE) FORCE
	cd terminal\ && $(MAKE) -f $(MAKEFILE) clean
sub-terminal-clean: terminal\$(MAKEFILE) FORCE
	cd terminal\ && $(MAKE) -f $(MAKEFILE) clean
sub-terminal-distclean-ordered: terminal\$(MAKEFILE) FORCE
	cd terminal\ && $(MAKE) -f $(MAKEFILE) distclean
sub-terminal-distclean: terminal\$(MAKEFILE) FORCE
	cd terminal\ && $(MAKE) -f $(MAKEFILE) distclean
sub-terminal-install_subtargets-ordered: terminal\$(MAKEFILE) FORCE
	cd terminal\ && $(MAKE) -f $(MAKEFILE) install
sub-terminal-install_subtargets: terminal\$(MAKEFILE) FORCE
	cd terminal\ && $(MAKE) -f $(MAKEFILE) install
sub-terminal-uninstall_subtargets-ordered: terminal\$(MAKEFILE) FORCE
	cd terminal\ && $(MAKE) -f $(MAKEFILE) uninstall
sub-terminal-uninstall_subtargets: terminal\$(MAKEFILE) FORCE
	cd terminal\ && $(MAKE) -f $(MAKEFILE) uninstall
..\Neodymium\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) ..\Neodymium\ $(MKDIR) ..\Neodymium\ 
	cd ..\Neodymium\ && $(QMAKE) e:\shaka\dev\current\soft\Neodymium\Neodymium.pro -spec e:\dev\QtSDK\Desktop\Qt\4.8.1\mingw\mkspecs\win32-g++ CONFIG+=declarative_debug -o $(MAKEFILE)
sub----Neodymium-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) ..\Neodymium\ $(MKDIR) ..\Neodymium\ 
	cd ..\Neodymium\ && $(QMAKE) e:\shaka\dev\current\soft\Neodymium\Neodymium.pro -spec e:\dev\QtSDK\Desktop\Qt\4.8.1\mingw\mkspecs\win32-g++ CONFIG+=declarative_debug -o $(MAKEFILE)
sub----Neodymium: ..\Neodymium\$(MAKEFILE) FORCE
	cd ..\Neodymium\ && $(MAKE) -f $(MAKEFILE)
sub----Neodymium-make_default-ordered: ..\Neodymium\$(MAKEFILE) sub-terminal-make_default-ordered  FORCE
	cd ..\Neodymium\ && $(MAKE) -f $(MAKEFILE) 
sub----Neodymium-make_default: ..\Neodymium\$(MAKEFILE) FORCE
	cd ..\Neodymium\ && $(MAKE) -f $(MAKEFILE) 
sub----Neodymium-make_first-ordered: ..\Neodymium\$(MAKEFILE) sub-terminal-make_first-ordered  FORCE
	cd ..\Neodymium\ && $(MAKE) -f $(MAKEFILE) first
sub----Neodymium-make_first: ..\Neodymium\$(MAKEFILE) FORCE
	cd ..\Neodymium\ && $(MAKE) -f $(MAKEFILE) first
sub----Neodymium-all-ordered: ..\Neodymium\$(MAKEFILE) sub-terminal-all-ordered  FORCE
	cd ..\Neodymium\ && $(MAKE) -f $(MAKEFILE) all
sub----Neodymium-all: ..\Neodymium\$(MAKEFILE) FORCE
	cd ..\Neodymium\ && $(MAKE) -f $(MAKEFILE) all
sub----Neodymium-clean-ordered: ..\Neodymium\$(MAKEFILE) sub-terminal-clean-ordered  FORCE
	cd ..\Neodymium\ && $(MAKE) -f $(MAKEFILE) clean
sub----Neodymium-clean: ..\Neodymium\$(MAKEFILE) FORCE
	cd ..\Neodymium\ && $(MAKE) -f $(MAKEFILE) clean
sub----Neodymium-distclean-ordered: ..\Neodymium\$(MAKEFILE) sub-terminal-distclean-ordered  FORCE
	cd ..\Neodymium\ && $(MAKE) -f $(MAKEFILE) distclean
sub----Neodymium-distclean: ..\Neodymium\$(MAKEFILE) FORCE
	cd ..\Neodymium\ && $(MAKE) -f $(MAKEFILE) distclean
sub----Neodymium-install_subtargets-ordered: ..\Neodymium\$(MAKEFILE) sub-terminal-install_subtargets-ordered  FORCE
	cd ..\Neodymium\ && $(MAKE) -f $(MAKEFILE) install
sub----Neodymium-install_subtargets: ..\Neodymium\$(MAKEFILE) FORCE
	cd ..\Neodymium\ && $(MAKE) -f $(MAKEFILE) install
sub----Neodymium-uninstall_subtargets-ordered: ..\Neodymium\$(MAKEFILE) sub-terminal-uninstall_subtargets-ordered  FORCE
	cd ..\Neodymium\ && $(MAKE) -f $(MAKEFILE) uninstall
sub----Neodymium-uninstall_subtargets: ..\Neodymium\$(MAKEFILE) FORCE
	cd ..\Neodymium\ && $(MAKE) -f $(MAKEFILE) uninstall
manager\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) manager\ $(MKDIR) manager\ 
	cd manager\ && $(QMAKE) e:\shaka\dev\current\soft\BlueSystem\manager\manager.pro -spec e:\dev\QtSDK\Desktop\Qt\4.8.1\mingw\mkspecs\win32-g++ CONFIG+=declarative_debug -o $(MAKEFILE)
sub-manager-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) manager\ $(MKDIR) manager\ 
	cd manager\ && $(QMAKE) e:\shaka\dev\current\soft\BlueSystem\manager\manager.pro -spec e:\dev\QtSDK\Desktop\Qt\4.8.1\mingw\mkspecs\win32-g++ CONFIG+=declarative_debug -o $(MAKEFILE)
sub-manager: manager\$(MAKEFILE) FORCE
	cd manager\ && $(MAKE) -f $(MAKEFILE)
sub-manager-make_default-ordered: manager\$(MAKEFILE) sub----Neodymium-make_default-ordered  FORCE
	cd manager\ && $(MAKE) -f $(MAKEFILE) 
sub-manager-make_default: manager\$(MAKEFILE) FORCE
	cd manager\ && $(MAKE) -f $(MAKEFILE) 
sub-manager-make_first-ordered: manager\$(MAKEFILE) sub----Neodymium-make_first-ordered  FORCE
	cd manager\ && $(MAKE) -f $(MAKEFILE) first
sub-manager-make_first: manager\$(MAKEFILE) FORCE
	cd manager\ && $(MAKE) -f $(MAKEFILE) first
sub-manager-all-ordered: manager\$(MAKEFILE) sub----Neodymium-all-ordered  FORCE
	cd manager\ && $(MAKE) -f $(MAKEFILE) all
sub-manager-all: manager\$(MAKEFILE) FORCE
	cd manager\ && $(MAKE) -f $(MAKEFILE) all
sub-manager-clean-ordered: manager\$(MAKEFILE) sub----Neodymium-clean-ordered  FORCE
	cd manager\ && $(MAKE) -f $(MAKEFILE) clean
sub-manager-clean: manager\$(MAKEFILE) FORCE
	cd manager\ && $(MAKE) -f $(MAKEFILE) clean
sub-manager-distclean-ordered: manager\$(MAKEFILE) sub----Neodymium-distclean-ordered  FORCE
	cd manager\ && $(MAKE) -f $(MAKEFILE) distclean
sub-manager-distclean: manager\$(MAKEFILE) FORCE
	cd manager\ && $(MAKE) -f $(MAKEFILE) distclean
sub-manager-install_subtargets-ordered: manager\$(MAKEFILE) sub----Neodymium-install_subtargets-ordered  FORCE
	cd manager\ && $(MAKE) -f $(MAKEFILE) install
sub-manager-install_subtargets: manager\$(MAKEFILE) FORCE
	cd manager\ && $(MAKE) -f $(MAKEFILE) install
sub-manager-uninstall_subtargets-ordered: manager\$(MAKEFILE) sub----Neodymium-uninstall_subtargets-ordered  FORCE
	cd manager\ && $(MAKE) -f $(MAKEFILE) uninstall
sub-manager-uninstall_subtargets: manager\$(MAKEFILE) FORCE
	cd manager\ && $(MAKE) -f $(MAKEFILE) uninstall
updater\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) updater\ $(MKDIR) updater\ 
	cd updater\ && $(QMAKE) e:\shaka\dev\current\soft\BlueSystem\updater\updater.pro -spec e:\dev\QtSDK\Desktop\Qt\4.8.1\mingw\mkspecs\win32-g++ CONFIG+=declarative_debug -o $(MAKEFILE)
sub-updater-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) updater\ $(MKDIR) updater\ 
	cd updater\ && $(QMAKE) e:\shaka\dev\current\soft\BlueSystem\updater\updater.pro -spec e:\dev\QtSDK\Desktop\Qt\4.8.1\mingw\mkspecs\win32-g++ CONFIG+=declarative_debug -o $(MAKEFILE)
sub-updater: updater\$(MAKEFILE) FORCE
	cd updater\ && $(MAKE) -f $(MAKEFILE)
sub-updater-make_default-ordered: updater\$(MAKEFILE) sub-manager-make_default-ordered  FORCE
	cd updater\ && $(MAKE) -f $(MAKEFILE) 
sub-updater-make_default: updater\$(MAKEFILE) FORCE
	cd updater\ && $(MAKE) -f $(MAKEFILE) 
sub-updater-make_first-ordered: updater\$(MAKEFILE) sub-manager-make_first-ordered  FORCE
	cd updater\ && $(MAKE) -f $(MAKEFILE) first
sub-updater-make_first: updater\$(MAKEFILE) FORCE
	cd updater\ && $(MAKE) -f $(MAKEFILE) first
sub-updater-all-ordered: updater\$(MAKEFILE) sub-manager-all-ordered  FORCE
	cd updater\ && $(MAKE) -f $(MAKEFILE) all
sub-updater-all: updater\$(MAKEFILE) FORCE
	cd updater\ && $(MAKE) -f $(MAKEFILE) all
sub-updater-clean-ordered: updater\$(MAKEFILE) sub-manager-clean-ordered  FORCE
	cd updater\ && $(MAKE) -f $(MAKEFILE) clean
sub-updater-clean: updater\$(MAKEFILE) FORCE
	cd updater\ && $(MAKE) -f $(MAKEFILE) clean
sub-updater-distclean-ordered: updater\$(MAKEFILE) sub-manager-distclean-ordered  FORCE
	cd updater\ && $(MAKE) -f $(MAKEFILE) distclean
sub-updater-distclean: updater\$(MAKEFILE) FORCE
	cd updater\ && $(MAKE) -f $(MAKEFILE) distclean
sub-updater-install_subtargets-ordered: updater\$(MAKEFILE) sub-manager-install_subtargets-ordered  FORCE
	cd updater\ && $(MAKE) -f $(MAKEFILE) install
sub-updater-install_subtargets: updater\$(MAKEFILE) FORCE
	cd updater\ && $(MAKE) -f $(MAKEFILE) install
sub-updater-uninstall_subtargets-ordered: updater\$(MAKEFILE) sub-manager-uninstall_subtargets-ordered  FORCE
	cd updater\ && $(MAKE) -f $(MAKEFILE) uninstall
sub-updater-uninstall_subtargets: updater\$(MAKEFILE) FORCE
	cd updater\ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: BlueSystem.pro  e:/dev/QtSDK/Desktop/Qt/4.8.1/mingw/mkspecs/win32-g++/qmake.conf e:/dev/QtSDK/Desktop/Qt/4.8.1/mingw/mkspecs/qconfig.pri \
		e:/dev/QtSDK/Desktop/Qt/4.8.1/mingw/mkspecs/modules/qt_webkit_version.pri \
		e:/dev/QtSDK/Desktop/Qt/4.8.1/mingw/mkspecs/features/qt_functions.prf \
		e:/dev/QtSDK/Desktop/Qt/4.8.1/mingw/mkspecs/features/qt_config.prf \
		e:/dev/QtSDK/Desktop/Qt/4.8.1/mingw/mkspecs/features/exclusive_builds.prf \
		e:/dev/QtSDK/Desktop/Qt/4.8.1/mingw/mkspecs/features/default_pre.prf \
		e:/dev/QtSDK/Desktop/Qt/4.8.1/mingw/mkspecs/features/win32/default_pre.prf \
		e:/dev/QtSDK/Desktop/Qt/4.8.1/mingw/mkspecs/features/debug.prf \
		e:/dev/QtSDK/Desktop/Qt/4.8.1/mingw/mkspecs/features/debug_and_release.prf \
		e:/dev/QtSDK/Desktop/Qt/4.8.1/mingw/mkspecs/features/default_post.prf \
		e:/dev/QtSDK/Desktop/Qt/4.8.1/mingw/mkspecs/features/win32/default_post.prf \
		e:/dev/QtSDK/Desktop/Qt/4.8.1/mingw/mkspecs/features/declarative_debug.prf \
		e:/dev/QtSDK/Desktop/Qt/4.8.1/mingw/mkspecs/features/win32/rtti.prf \
		e:/dev/QtSDK/Desktop/Qt/4.8.1/mingw/mkspecs/features/win32/exceptions.prf \
		e:/dev/QtSDK/Desktop/Qt/4.8.1/mingw/mkspecs/features/win32/stl.prf \
		e:/dev/QtSDK/Desktop/Qt/4.8.1/mingw/mkspecs/features/shared.prf \
		e:/dev/QtSDK/Desktop/Qt/4.8.1/mingw/mkspecs/features/warn_on.prf \
		e:/dev/QtSDK/Desktop/Qt/4.8.1/mingw/mkspecs/features/qt.prf \
		e:/dev/QtSDK/Desktop/Qt/4.8.1/mingw/mkspecs/features/win32/thread.prf \
		e:/dev/QtSDK/Desktop/Qt/4.8.1/mingw/mkspecs/features/moc.prf \
		e:/dev/QtSDK/Desktop/Qt/4.8.1/mingw/mkspecs/features/win32/windows.prf \
		e:/dev/QtSDK/Desktop/Qt/4.8.1/mingw/mkspecs/features/resources.prf \
		e:/dev/QtSDK/Desktop/Qt/4.8.1/mingw/mkspecs/features/uic.prf \
		e:/dev/QtSDK/Desktop/Qt/4.8.1/mingw/mkspecs/features/yacc.prf \
		e:/dev/QtSDK/Desktop/Qt/4.8.1/mingw/mkspecs/features/lex.prf \
		e:/dev/QtSDK/Desktop/Qt/4.8.1/mingw/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec e:\dev\QtSDK\Desktop\Qt\4.8.1\mingw\mkspecs\win32-g++ CONFIG+=declarative_debug -o Makefile BlueSystem.pro
e:\dev\QtSDK\Desktop\Qt\4.8.1\mingw\mkspecs\qconfig.pri:
e:\dev\QtSDK\Desktop\Qt\4.8.1\mingw\mkspecs\modules\qt_webkit_version.pri:
e:\dev\QtSDK\Desktop\Qt\4.8.1\mingw\mkspecs\features\qt_functions.prf:
e:\dev\QtSDK\Desktop\Qt\4.8.1\mingw\mkspecs\features\qt_config.prf:
e:\dev\QtSDK\Desktop\Qt\4.8.1\mingw\mkspecs\features\exclusive_builds.prf:
e:\dev\QtSDK\Desktop\Qt\4.8.1\mingw\mkspecs\features\default_pre.prf:
e:\dev\QtSDK\Desktop\Qt\4.8.1\mingw\mkspecs\features\win32\default_pre.prf:
e:\dev\QtSDK\Desktop\Qt\4.8.1\mingw\mkspecs\features\debug.prf:
e:\dev\QtSDK\Desktop\Qt\4.8.1\mingw\mkspecs\features\debug_and_release.prf:
e:\dev\QtSDK\Desktop\Qt\4.8.1\mingw\mkspecs\features\default_post.prf:
e:\dev\QtSDK\Desktop\Qt\4.8.1\mingw\mkspecs\features\win32\default_post.prf:
e:\dev\QtSDK\Desktop\Qt\4.8.1\mingw\mkspecs\features\declarative_debug.prf:
e:\dev\QtSDK\Desktop\Qt\4.8.1\mingw\mkspecs\features\win32\rtti.prf:
e:\dev\QtSDK\Desktop\Qt\4.8.1\mingw\mkspecs\features\win32\exceptions.prf:
e:\dev\QtSDK\Desktop\Qt\4.8.1\mingw\mkspecs\features\win32\stl.prf:
e:\dev\QtSDK\Desktop\Qt\4.8.1\mingw\mkspecs\features\shared.prf:
e:\dev\QtSDK\Desktop\Qt\4.8.1\mingw\mkspecs\features\warn_on.prf:
e:\dev\QtSDK\Desktop\Qt\4.8.1\mingw\mkspecs\features\qt.prf:
e:\dev\QtSDK\Desktop\Qt\4.8.1\mingw\mkspecs\features\win32\thread.prf:
e:\dev\QtSDK\Desktop\Qt\4.8.1\mingw\mkspecs\features\moc.prf:
e:\dev\QtSDK\Desktop\Qt\4.8.1\mingw\mkspecs\features\win32\windows.prf:
e:\dev\QtSDK\Desktop\Qt\4.8.1\mingw\mkspecs\features\resources.prf:
e:\dev\QtSDK\Desktop\Qt\4.8.1\mingw\mkspecs\features\uic.prf:
e:\dev\QtSDK\Desktop\Qt\4.8.1\mingw\mkspecs\features\yacc.prf:
e:\dev\QtSDK\Desktop\Qt\4.8.1\mingw\mkspecs\features\lex.prf:
e:\dev\QtSDK\Desktop\Qt\4.8.1\mingw\mkspecs\features\include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec e:\dev\QtSDK\Desktop\Qt\4.8.1\mingw\mkspecs\win32-g++ CONFIG+=declarative_debug -o Makefile BlueSystem.pro

qmake_all: sub-terminal-qmake_all sub----Neodymium-qmake_all sub-manager-qmake_all sub-updater-qmake_all FORCE

make_default: sub-terminal-make_default-ordered sub----Neodymium-make_default-ordered sub-manager-make_default-ordered sub-updater-make_default-ordered FORCE
make_first: sub-terminal-make_first-ordered sub----Neodymium-make_first-ordered sub-manager-make_first-ordered sub-updater-make_first-ordered FORCE
all: sub-terminal-all-ordered sub----Neodymium-all-ordered sub-manager-all-ordered sub-updater-all-ordered FORCE
clean: sub-terminal-clean-ordered sub----Neodymium-clean-ordered sub-manager-clean-ordered sub-updater-clean-ordered FORCE
distclean: sub-terminal-distclean-ordered sub----Neodymium-distclean-ordered sub-manager-distclean-ordered sub-updater-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-terminal-install_subtargets-ordered sub----Neodymium-install_subtargets-ordered sub-manager-install_subtargets-ordered sub-updater-install_subtargets-ordered FORCE
uninstall_subtargets: sub-terminal-uninstall_subtargets-ordered sub----Neodymium-uninstall_subtargets-ordered sub-manager-uninstall_subtargets-ordered sub-updater-uninstall_subtargets-ordered FORCE

sub-terminal-sub_Debug_ordered: terminal\$(MAKEFILE)
	cd terminal\ && $(MAKE) -f $(MAKEFILE) debug
sub----Neodymium-sub_Debug_ordered: ..\Neodymium\$(MAKEFILE) sub-terminal-sub_Debug_ordered 
	cd ..\Neodymium\ && $(MAKE) -f $(MAKEFILE) debug
sub-manager-sub_Debug_ordered: manager\$(MAKEFILE) sub----Neodymium-sub_Debug_ordered 
	cd manager\ && $(MAKE) -f $(MAKEFILE) debug
sub-updater-sub_Debug_ordered: updater\$(MAKEFILE) sub-manager-sub_Debug_ordered 
	cd updater\ && $(MAKE) -f $(MAKEFILE) debug
debug: sub-terminal-sub_Debug_ordered sub----Neodymium-sub_Debug_ordered sub-manager-sub_Debug_ordered sub-updater-sub_Debug_ordered

sub-terminal-sub_Release_ordered: terminal\$(MAKEFILE)
	cd terminal\ && $(MAKE) -f $(MAKEFILE) release
sub----Neodymium-sub_Release_ordered: ..\Neodymium\$(MAKEFILE) sub-terminal-sub_Release_ordered 
	cd ..\Neodymium\ && $(MAKE) -f $(MAKEFILE) release
sub-manager-sub_Release_ordered: manager\$(MAKEFILE) sub----Neodymium-sub_Release_ordered 
	cd manager\ && $(MAKE) -f $(MAKEFILE) release
sub-updater-sub_Release_ordered: updater\$(MAKEFILE) sub-manager-sub_Release_ordered 
	cd updater\ && $(MAKE) -f $(MAKEFILE) release
release: sub-terminal-sub_Release_ordered sub----Neodymium-sub_Release_ordered sub-manager-sub_Release_ordered sub-updater-sub_Release_ordered

sub-terminal-check_ordered: terminal\$(MAKEFILE)
	cd terminal\ && $(MAKE) -f $(MAKEFILE) check
sub----Neodymium-check_ordered: ..\Neodymium\$(MAKEFILE) sub-terminal-check_ordered 
	cd ..\Neodymium\ && $(MAKE) -f $(MAKEFILE) check
sub-manager-check_ordered: manager\$(MAKEFILE) sub----Neodymium-check_ordered 
	cd manager\ && $(MAKE) -f $(MAKEFILE) check
sub-updater-check_ordered: updater\$(MAKEFILE) sub-manager-check_ordered 
	cd updater\ && $(MAKE) -f $(MAKEFILE) check
check: sub-terminal-check_ordered sub----Neodymium-check_ordered sub-manager-check_ordered sub-updater-check_ordered

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

